In [1]:
import torch
import torch.nn as nn
import torch.optim as optim

import torchvision
import torchvision.transforms as transforms
from torchvision import datasets
from tqdm.notebook import tqdm
import numpy as np
import matplotlib.pyplot as plt
from genetic import Genetic

In [2]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(device)

cuda:0


In [3]:
train_set = torchvision.datasets.MNIST(
    root='./datasets/',
    train=True,
    download=True,
    transform=transforms.ToTensor()
)
test_set = torchvision.datasets.MNIST(
    root='./datasets/',
    train=False,
    download=True,
    transform=transforms.ToTensor()
)

train_loader = torch.utils.data.DataLoader(train_set, batch_size=100, shuffle=True)
test_loader = torch.utils.data.DataLoader(test_set, batch_size=100, shuffle=True)



In [4]:
#values to change
pop_size = 10
num_generations = 5
epochs = 5
nparents = 5

max_nfilters = 80
max_sfilters = 10
nlayers = 2

total = len(test_set)

In [ ]:
genCNN = Genetic(pop_size,nlayers,max_nfilters,max_sfilters)
pop = genCNN.generate_population()
for i in range(num_generations+1):
    print('GENERATION: {}'.format(i))
    print(pop)
    pop_acc, best_model = genCNN.fitness(pop,train_loader,test_loader,epochs, total)
    print('Best Accuracy at the generation {}: {}'.format(i,genCNN.max_acc))
    torch.save(best_model, 'model_gen_{}.pt'.format(i))
    parents = genCNN.select_parents(pop,nparents,pop_acc.copy())
    child = genCNN.crossover(parents)
    child = genCNN.mutation(child)
    pop = np.concatenate((parents,child),axis=0).astype('int')

GENERATION: 0
[[45 48  4  1]
 [65 68  4  6]
 [68 10  1  3]
 [22 37  4  9]
 [71 13  2  4]
 [59 66  4  4]
 [40 47  8  1]
 [38 26  2  1]
 [78 73  5  8]
 [10 21  4  3]]
Person: 0, Name: [45 48], [4 1]
EPOCH 1:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 2:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 3:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 4:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 5:


  0%|          | 0/600 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

Person: 1, Name: [65 68], [4 6]
EPOCH 1:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 2:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 3:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 4:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 5:


  0%|          | 0/600 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

Person: 2, Name: [68 10], [1 3]
EPOCH 1:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 2:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 3:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 4:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 5:


  0%|          | 0/600 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

Person: 3, Name: [22 37], [4 9]
EPOCH 1:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 2:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 3:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 4:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 5:


  0%|          | 0/600 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

Person: 4, Name: [71 13], [2 4]
EPOCH 1:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 2:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 3:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 4:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 5:


  0%|          | 0/600 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

Person: 5, Name: [59 66], [4 4]
EPOCH 1:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 2:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 3:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 4:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 5:


  0%|          | 0/600 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

Person: 6, Name: [40 47], [8 1]
EPOCH 1:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 2:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 3:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 4:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 5:


  0%|          | 0/600 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

Person: 7, Name: [38 26], [2 1]
EPOCH 1:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 2:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 3:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 4:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 5:


  0%|          | 0/600 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

Person: 8, Name: [78 73], [5 8]
EPOCH 1:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 2:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 3:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 4:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 5:


  0%|          | 0/600 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

Person: 9, Name: [10 21], [4 3]
EPOCH 1:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 2:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 3:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 4:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 5:


  0%|          | 0/600 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

Best Accuracy at the generation 0: 94.81999969482422
GENERATION: 1
[[59 66  4  4]
 [71 13  2  4]
 [45 48  4  1]
 [40 47  8  1]
 [38 26  2  1]
 [60 16  4  4]
 [72 48  3  1]
 [47 44  4  1]
 [41 26 10  1]
 [39 64  2  4]]
Person: 0, Name: [59 66], [4 4]
EPOCH 1:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 2:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 3:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 4:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 5:


  0%|          | 0/600 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

Person: 1, Name: [71 13], [2 4]
EPOCH 1:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 2:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 3:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 4:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 5:


  0%|          | 0/600 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

Person: 2, Name: [45 48], [4 1]
EPOCH 1:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 2:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 3:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 4:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 5:


  0%|          | 0/600 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

Person: 3, Name: [40 47], [8 1]
EPOCH 1:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 2:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 3:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 4:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 5:


  0%|          | 0/600 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

Person: 4, Name: [38 26], [2 1]
EPOCH 1:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 2:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 3:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 4:


  0%|          | 0/600 [00:00<?, ?it/s]