In [1]:
import torch
import torch.nn as nn
import torch.optim as optim

import torchvision
import torchvision.transforms as transforms
from torchvision import datasets
from tqdm.notebook import tqdm
from new_network import BasicBlock, ResNet
import numpy as np
import matplotlib.pyplot as plt
from genetic import Genetic

In [2]:
EPOCHS = 5
train_set = torchvision.datasets.MNIST(
    root='./datasets/',
    train=True,
    download=True,
    transform=transforms.ToTensor()
)
test_set = torchvision.datasets.MNIST(
    root='./datasets/',
    train=False,
    download=True,
    transform=transforms.ToTensor()
)
train_loader = torch.utils.data.DataLoader(train_set, batch_size=100, shuffle=True)
test_loader = torch.utils.data.DataLoader(test_set, batch_size=100, shuffle=True)
#channels = [16, 32]
#kSizes = [5, 5]
"""
model = ResNet(BasicBlock, [3, 3, 3])
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.1)"""

'\nmodel = ResNet(BasicBlock, [3, 3, 3])\ncriterion = nn.CrossEntropyLoss()\noptimizer = torch.optim.SGD(model.parameters(), lr=0.1)'

In [3]:
"""for epoch in range(EPOCHS):
    print('EPOCH {}:'.format(epoch + 1))
    for images, labels in tqdm(train_loader):
        optimizer.zero_grad()
        output = model(images)
        loss = criterion(output, labels)
        loss.backward()
        optimizer.step()"""

"for epoch in range(EPOCHS):\n    print('EPOCH {}:'.format(epoch + 1))\n    for images, labels in tqdm(train_loader):\n        optimizer.zero_grad()\n        output = model(images)\n        loss = criterion(output, labels)\n        loss.backward()\n        optimizer.step()"

In [4]:
#model.eval()

In [5]:
"""correct = 0
with torch.no_grad():
    # Iterate through test set minibatchs 
    for images, labels in tqdm(test_loader):
        # Forward pass
        output = model(images)
        
        predictions = torch.argmax(output, dim=1)
        correct += torch.sum((predictions == labels).float())
    
print('Test accuracy: {}'.format(correct/total))"""

"correct = 0\nwith torch.no_grad():\n    # Iterate through test set minibatchs \n    for images, labels in tqdm(test_loader):\n        # Forward pass\n        output = model(images)\n        \n        predictions = torch.argmax(output, dim=1)\n        correct += torch.sum((predictions == labels).float())\n    \nprint('Test accuracy: {}'.format(correct/total))"

In [6]:
#torch.save(model.state_dict(), 'model.pth')

In [7]:
pop_size = 10
nlayers = 2
max_nfilters = 80
max_sfilters = 10
epochs = 5
num_generations = 10
total = len(test_set)
genCNN = Genetic(pop_size,nlayers,max_nfilters,max_sfilters)
pop = genCNN.generate_population()

print(pop)

for i in range(num_generations+1):
    pop_acc = genCNN.fitness(pop,train_loader,test_loader,EPOCHS, total)
    print('Best Accuracy at the generation {}: {}'.format(i,genCNN.max_acc))
    parents = genCNN.select_parents(pop,5,pop_acc.copy())
    child = genCNN.crossover(parents)
    child = genCNN.mutation(child)
    pop = np.concatenate((parents,child),axis=0).astype('int')

[[45 48  4  1]
 [65 68  4  6]
 [68 10  1  3]
 [22 37  4  9]
 [71 13  2  4]
 [59 66  4  4]
 [40 47  8  1]
 [38 26  2  1]
 [78 73  5  8]
 [10 21  4  3]]
EPOCH 1:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 2:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 3:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 4:


  0%|          | 0/600 [00:00<?, ?it/s]

EPOCH 5:


  0%|          | 0/600 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

EPOCH 1:


  0%|          | 0/600 [00:00<?, ?it/s]

RuntimeError: mat1 and mat2 shapes cannot be multiplied (100x612 and 1728x256)